In [138]:
import pandas as pd

df_july = pd.read_excel('/Users/flatironschool/Downloads/SNAP_zip/JUL 2010.xls', header=None)
df_jan = pd.read_excel('/Users/flatironschool/Downloads/SNAP_zip/Jan 2010.xls', header=None)

In [139]:
# CLEANING JANUARY TABLE

In [140]:
jan = df_jan.iloc[4:].drop(columns=[2,4,6,7,8,9,10,11,12,13]).dropna()
jan.columns = ['County Info', 'SNAP Public Assistance Participation', 'SNAP Non-Public Assistance Participation', 'Total SNAP PA and Non-PA']

In [141]:
cleaned_counties = []
for county in jan['County Info']:
    county = county[8:11] + county[15:]
    cleaned_counties.append(county)

In [142]:
jan['new county info'] = cleaned_counties

In [143]:
states = []
for county in jan['new county info']: 
    states.append(county[:3].strip())
    
jan['States'] = states

In [144]:
just_counties = []
for county in jan['new county info']: 
    just_counties.append(county[3:])
    
jan['Counties'] = just_counties

In [145]:
jan = jan.reset_index(drop=True)
jan.drop(columns=['new county info', 'County Info'])

,SNAP Public Assistance Participation,SNAP Non-Public Assistance Participation,Total SNAP PA and Non-PA,States,Counties
0,838,6129,6967,AL,AUTAUGA CO FS OFF
1,1565,16476,18041,AL,BALDWIN CO FS OFF
2,1096,4943,6039,AL,BARBOUR CO FS OFF
3,613,3132,3745,AL,BIBB CO FS OFF
4,1062,6970,8032,AL,BLOUNT CO FS OFF
5,612,2160,2772,AL,BULLOCK CO FS OFF
6,895,4198,5093,AL,BUTLER CO FSO
7,3536,20060,23596,AL,CALHOUN CO FS OFF
8,1239,6696,7935,AL,CHAMBERS CO FS OFF
9,694,4196,4890,AL,CHEROKEE CO FS OFFICE
10,1164,7961,9125,AL,CHILTON CO FS OFF
11,502,2680,3182,AL,CHOCTAW CO FS OFF
12,1146,4720,5866,AL,CLARKE CO FS OFF.
13,275,1770,2045,AL,CLAY CO FS OFF
14,304,2017,2321,AL,CLEBURNE CO FS OFF
15,757,4836,5593,AL,COFFEE CO FS OFF
16,1163,7472,8635,AL,COLBERT CO FS OFF
17,657,3520,4177,AL,CONECUH CO FS OFF
18,295,1725,2020,AL,COOSA CO FSO
19,960,6601,7561,AL,COVINGTON CO FS OFF
20,509,2293,2802,AL,CRENSHAW CO FSO
21,1418,9408,10826,AL,CULLMAN CO FS OFF
22,1586,8266,9852,AL,DALE CO FS OFF
23,3529,12596,16125,AL,DALLAS CO FS OFF
24,1193,10904,12097,AL,DEKALB CO FS OFF
25,1446,8840,10286,AL,ELMORE CO FS OFF
26,1126,7803,8929,AL,ESCAMBIA CO FS OFF
27,2244,14141,16385,AL,ETOWQH CO FS OFF
28,715,2934,3649,AL,FAYETTE CO FS OFF
29,806,5241,6047,AL,FRANKLIN CO FS OFF
...,...,...,...,...,...
2523,2215,27143,29358,WI,RACINE CO DSS
2524,217,2383,2600,WI,RICHLAND CO DSS
2525,1764,24325,26089,WI,ROCK CO DSS
2526,157,2607,2764,WI,RUSK CO DSS
2527,189,5281,5470,WI,ST CROIX CO DSS
2528,352,6098,6450,WI,SAUK CO DSS
2529,160,3146,3306,WI,SAWYER CO DSS
2530,268,4228,4496,WI,SHAWANO CO DSS
2531,696,11487,12183,WI,SHEBOYGAN CO DSS
2532,138,2320,2458,WI,TAYLOR CO DSS
2533,161,2758,2919,WI,TREMPEALEAU CO DSS
2534,181,2737,2918,WI,VERNON CO DSS
2535,121,1793,1914,WI,VILAS CO DSS
2536,403,10164,10567,WI,WALWORTH CO DSS
2537,174,2488,2662,WI,WASHBURN CO DSS
2538,333,8000,8333,WI,WASHINGTON CO DSS
2539,725,13328,14053,WI,WAUKESHA CO DSS
2540,303,4818,5121,WI,WAUPACA CO DSS
2541,194,2861,3055,WI,WAUSHARA CO DSS
2542,990,14476,15466,WI,WINNEBAGO CO DSS
2543,618,8854,9472,WI,WOOD CO DSS
2544,91,2397,2488,WI,ONEIDA TRIBAL COUNCIL
2545,7,225,232,WI,STOCKBRIDGE-MUNSEE TRI
2546,33,584,617,WI,RED CLIFF TRIBAL COUNC
2547,11,586,597,WI,BAD RIVER TRIBAL COUNC
2548,44,1331,1375,WI,LAC DU FLAMBEAU TRIBAL
2549,13,216,229,WI,SOKAOGON TRIBAL AGENCY
2550,2,75,77,WI,POTAWATOMI TRIBE
2551,668,33826,34494,WY,WYOMING SD PASS
2552,7780104,31635995,39416099,mar,

In [146]:
# CLEANING JULY SNAP TABLE

In [147]:
july = df_july.iloc[4:].drop(columns=[2,4,6,7,8,9,10,11,12,13]).dropna()
july.columns = ['County Info', 'SNAP Public Assistance Participation', 'SNAP Non-Public Assistance Participation', 'Total SNAP PA and Non-PA']

cleaned_counties = []
for county in july['County Info']:
    county = county[8:11] + county[15:]
    cleaned_counties.append(county)
    
july['new county info'] = cleaned_counties 
    
states = []
for county in july['new county info']: 
    states.append(county[:3].strip())
    
july['States'] = states

just_counties = []
for county in july['new county info']: 
    just_counties.append(county[3:])
    
july['Counties'] = just_counties

july = july.reset_index(drop=True)
july.drop(columns=['new county info', 'County Info'])

,SNAP Public Assistance Participation,SNAP Non-Public Assistance Participation,Total SNAP PA and Non-PA,States,Counties
0,868,6270,7138,AL,AUTAUGA CO FS OFF
1,1671,17697,19368,AL,BALDWIN CO FS OFF
2,1041,4904,5945,AL,BARBOUR CO FS OFF
3,582,3321,3903,AL,BIBB CO FS OFF
4,984,7445,8429,AL,BLOUNT CO FS OFF
5,577,2280,2857,AL,BULLOCK CO FS OFF
6,871,4207,5078,AL,BUTLER CO FSO
7,3670,20067,23737,AL,CALHOUN CO FS OFF
8,1270,6709,7979,AL,CHAMBERS CO FS OFF
9,728,4393,5121,AL,CHEROKEE CO FS OFFICE
10,1107,8257,9364,AL,CHILTON CO FS OFF
11,503,2659,3162,AL,CHOCTAW CO FS OFF
12,1235,4753,5988,AL,CLARKE CO FS OFF.
13,292,1840,2132,AL,CLAY CO FS OFF
14,322,2162,2484,AL,CLEBURNE CO FS OFF
15,669,5324,5993,AL,COFFEE CO FS OFF
16,1196,7657,8853,AL,COLBERT CO FS OFF
17,627,3493,4120,AL,CONECUH CO FS OFF
18,287,1634,1921,AL,COOSA CO FSO
19,872,6808,7680,AL,COVINGTON CO FS OFF
20,436,2448,2884,AL,CRENSHAW CO FSO
21,1351,9710,11061,AL,CULLMAN CO FS OFF
22,1518,8356,9874,AL,DALE CO FS OFF
23,3395,13145,16540,AL,DALLAS CO FS OFF
24,1262,11600,12862,AL,DEKALB CO FS OFF
25,1402,9537,10939,AL,ELMORE CO FS OFF
26,1119,7995,9114,AL,ESCAMBIA CO FS OFF
27,2202,14728,16930,AL,ETOWQH CO FS OFF
28,712,3043,3755,AL,FAYETTE CO FS OFF
29,850,5453,6303,AL,FRANKLIN CO FS OFF
...,...,...,...,...,...
2572,2267,25489,27756,WI,RACINE CO DSS
2573,194,2316,2510,WI,RICHLAND CO DSS
2574,1737,22950,24687,WI,ROCK CO DSS
2575,161,2410,2571,WI,RUSK CO DSS
2576,211,5206,5417,WI,ST CROIX CO DSS
2577,348,6037,6385,WI,SAUK CO DSS
2578,147,2907,3054,WI,SAWYER CO DSS
2579,253,4017,4270,WI,SHAWANO CO DSS
2580,675,11176,11851,WI,SHEBOYGAN CO DSS
2581,128,2258,2386,WI,TAYLOR CO DSS
2582,145,2698,2843,WI,TREMPEALEAU CO DSS
2583,195,2647,2842,WI,VERNON CO DSS
2584,117,1713,1830,WI,VILAS CO DSS
2585,420,10108,10528,WI,WALWORTH CO DSS
2586,174,2378,2552,WI,WASHBURN CO DSS
2587,348,7632,7980,WI,WASHINGTON CO DSS
2588,749,13355,14104,WI,WAUKESHA CO DSS
2589,309,4711,5020,WI,WAUPACA CO DSS
2590,184,2708,2892,WI,WAUSHARA CO DSS
2591,969,13785,14754,WI,WINNEBAGO CO DSS
2592,609,8676,9285,WI,WOOD CO DSS
2593,104,2226,2330,WI,ONEIDA TRIBAL COUNCIL
2594,11,215,226,WI,STOCKBRIDGE-MUNSEE TRI
2595,29,569,598,WI,RED CLIFF TRIBAL COUNC
2596,8,473,481,WI,BAD RIVER TRIBAL COUNC
2597,63,1280,1343,WI,LAC DU FLAMBEAU TRIBAL
2598,13,216,229,WI,SOKAOGON TRIBAL AGENCY
2599,2,65,67,WI,POTAWATOMI TRIBE
2600,613,34706,35319,WY,WYOMING SD PASS
2601,8162142,33656178,41818320,mar,

In [148]:
# COMBINING JAN AND JULY TABLES

In [149]:
merged = pd.merge(jan,july, on='Counties')

merged['Jan & July Public Assist. Participation'] = merged['SNAP Public Assistance Participation_x'] + merged['SNAP Public Assistance Participation_y']

merged['Jan & July Non-Public Assist. Participation'] = merged['SNAP Non-Public Assistance Participation_x'] + merged['SNAP Non-Public Assistance Participation_y']

merged['Jan & July TOTAL Assist. Participation'] = merged['Total SNAP PA and Non-PA_x'] +  merged['Total SNAP PA and Non-PA_y']

something = merged.drop(columns=['County Info_x', 'County Info_y', 'new county info_x', 'States_x', 'new county info_y', 'Total SNAP PA and Non-PA_y', 'SNAP Non-Public Assistance Participation_y', 'SNAP Public Assistance Participation_y', 'Total SNAP PA and Non-PA_x',  'SNAP Non-Public Assistance Participation_x', 'SNAP Public Assistance Participation_x'])

something.rename(columns = {'States_y':'States'})

final = something.drop(something.index[3444])

final

,Counties,States_y,Jan & July Public Assist. Participation,Jan & July Non-Public Assist. Participation,Jan & July TOTAL Assist. Participation
0,AUTAUGA CO FS OFF,AL,1706,12399,14105
1,BALDWIN CO FS OFF,AL,3236,34173,37409
2,BARBOUR CO FS OFF,AL,2137,9847,11984
3,BIBB CO FS OFF,AL,1195,6453,7648
4,BLOUNT CO FS OFF,AL,2046,14415,16461
5,BULLOCK CO FS OFF,AL,1189,4440,5629
6,BUTLER CO FSO,AL,1766,8405,10171
7,CALHOUN CO FS OFF,AL,7206,40127,47333
8,CHAMBERS CO FS OFF,AL,2509,13405,15914
9,CHEROKEE CO FS OFFICE,AL,1422,8589,10011
10,CHILTON CO FS OFF,AL,2271,16218,18489
11,CHOCTAW CO FS OFF,AL,1005,5339,6344
12,CLARKE CO FS OFF.,AL,2381,9473,11854
13,CLAY CO FS OFF,AL,567,3610,4177
14,CLEBURNE CO FS OFF,AL,626,4179,4805
15,COFFEE CO FS OFF,AL,1426,10160,11586
16,COLBERT CO FS OFF,AL,2359,15129,17488
17,CONECUH CO FS OFF,AL,1284,7013,8297
18,COOSA CO FSO,AL,582,3359,3941
19,COVINGTON CO FS OFF,AL,1832,13409,15241
20,CRENSHAW CO FSO,AL,945,4741,5686
21,CULLMAN CO FS OFF,AL,2769,19118,21887
22,DALE CO FS OFF,AL,3104,16622,19726
23,DALLAS CO FS OFF,AL,6924,25741,32665
24,DEKALB CO FS OFF,AL,2455,22504,24959
25,ELMORE CO FS OFF,AL,2848,18377,21225
26,ESCAMBIA CO FS OFF,AL,2245,15798,18043
27,ETOWQH CO FS OFF,AL,4446,28869,33315
28,FAYETTE CO FS OFF,AL,1427,5977,7404
29,FRANKLIN CO FS OFF,AL,1656,10694,12350
...,...,...,...,...,...
3414,PORTAGE CO DSS,WI,659,11668,12327
3415,PRICE CO DSS,WI,286,3444,3730
3416,RACINE CO DSS,WI,4482,52632,57114
3417,RICHLAND CO DSS,WI,411,4699,5110
3418,ROCK CO DSS,WI,3501,47275,50776
3419,RUSK CO DSS,WI,318,5017,5335
3420,ST CROIX CO DSS,WI,400,10487,10887
3421,SAUK CO DSS,WI,700,12135,12835
3422,SAWYER CO DSS,WI,307,6053,6360
3423,SHAWANO CO DSS,WI,521,8245,8766
3424,SHEBOYGAN CO DSS,WI,1371,22663,24034
3425,TAYLOR CO DSS,WI,266,4578,4844
3426,TREMPEALEAU CO DSS,WI,306,5456,5762
3427,VERNON CO DSS,WI,376,5384,5760
3428,VILAS CO DSS,WI,238,3506,3744
3429,WALWORTH CO DSS,WI,823,20272,21095
3430,WASHBURN CO DSS,WI,348,4866,5214
3431,WAUKESHA CO DSS,WI,1474,26683,28157
3432,WAUPACA CO DSS,WI,612,9529,10141
3433,WAUSHARA CO DSS,WI,378,5569,5947
3434,WINNEBAGO CO DSS,WI,1959,28261,30220
3435,WOOD CO DSS,WI,1227,17530,18757
3436,ONEIDA TRIBAL COUNCIL,WI,195,4623,4818
3437,STOCKBRIDGE-MUNSEE TRI,WI,18,440,458
3438,RED CLIFF TRIBAL COUNC,WI,62,1153,1215
3439,BAD RIVER TRIBAL COUNC,WI,19,1059,1078
3440,LAC DU FLAMBEAU TRIBAL,WI,107,2611,2718
3441,SOKAOGON TRIBAL AGENCY,WI,26,432,458
3442,POTAWATOMI TRIBE,WI,4,140,144
3443,WYOMING SD PASS,WY,1281,68532,69813

In [150]:
# dropping all SNAP data except for total number because others seem superfluous
final = final.drop(columns=['Jan & July Public Assist. Participation', 'Jan & July Non-Public Assist. Participation'])

In [151]:
# renaming total SNAP feature to 'Total SNAP' for legibility
final = final.rename(columns={'Jan & July TOTAL Assist. Participation': 'Total SNAP', 'States_y': 'States'})

In [152]:
# viewing final
final

                    Counties States Total SNAP
0          AUTAUGA CO FS OFF     AL      14105
1          BALDWIN CO FS OFF     AL      37409
2          BARBOUR CO FS OFF     AL      11984
3             BIBB CO FS OFF     AL       7648
4           BLOUNT CO FS OFF     AL      16461
5          BULLOCK CO FS OFF     AL       5629
6              BUTLER CO FSO     AL      10171
7          CALHOUN CO FS OFF     AL      47333
8         CHAMBERS CO FS OFF     AL      15914
9      CHEROKEE CO FS OFFICE     AL      10011
10         CHILTON CO FS OFF     AL      18489
11         CHOCTAW CO FS OFF     AL       6344
12         CLARKE CO FS OFF.     AL      11854
13            CLAY CO FS OFF     AL       4177
14        CLEBURNE CO FS OFF     AL       4805
15          COFFEE CO FS OFF     AL      11586
16         COLBERT CO FS OFF     AL      17488
17         CONECUH CO FS OFF     AL       8297
18              COOSA CO FSO     AL       3941
19       COVINGTON CO FS OFF     AL      15241
20           CRENSHAW CO FSO     AL       5686
21         CULLMAN CO FS OFF     AL      21887
22            DALE CO FS OFF     AL      19726
23          DALLAS CO FS OFF     AL      32665
24          DEKALB CO FS OFF     AL      24959
25          ELMORE CO FS OFF     AL      21225
26        ESCAMBIA CO FS OFF     AL      18043
27          ETOWQH CO FS OFF     AL      33315
28         FAYETTE CO FS OFF     AL       7404
29        FRANKLIN CO FS OFF     AL      12350
...                      ...    ...        ...
3414          PORTAGE CO DSS     WI      12327
3415            PRICE CO DSS     WI       3730
3416           RACINE CO DSS     WI      57114
3417         RICHLAND CO DSS     WI       5110
3418             ROCK CO DSS     WI      50776
3419             RUSK CO DSS     WI       5335
3420         ST CROIX CO DSS     WI      10887
3421             SAUK CO DSS     WI      12835
3422           SAWYER CO DSS     WI       6360
3423          SHAWANO CO DSS     WI       8766
3424        SHEBOYGAN CO DSS     WI      24034
3425           TAYLOR CO DSS     WI       4844
3426      TREMPEALEAU CO DSS     WI       5762
3427           VERNON CO DSS     WI       5760
3428            VILAS CO DSS     WI       3744
3429         WALWORTH CO DSS     WI      21095
3430         WASHBURN CO DSS     WI       5214
3431         WAUKESHA CO DSS     WI      28157
3432          WAUPACA CO DSS     WI      10141
3433         WAUSHARA CO DSS     WI       5947
3434        WINNEBAGO CO DSS     WI      30220
3435             WOOD CO DSS     WI      18757
3436   ONEIDA TRIBAL COUNCIL     WI       4818
3437  STOCKBRIDGE-MUNSEE TRI     WI        458
3438  RED CLIFF TRIBAL COUNC     WI       1215
3439  BAD RIVER TRIBAL COUNC     WI       1078
3440  LAC DU FLAMBEAU TRIBAL     WI       2718
3441  SOKAOGON TRIBAL AGENCY     WI        458
3442        POTAWATOMI TRIBE     WI        144
3443         WYOMING SD PASS     WY      69813

[3444 rows x 3 columns]

In [153]:
# getting dictionary of states in order to turn state abbreviations into full state names
# states dictionary from http://code.activestate.com/recipes/577305-python-dictionary-of-us-states-and-territories/

states = {
        'AK': 'Alaska',
        'AL': 'Alabama',
        'AR': 'Arkansas',
        'AS': 'American Samoa',
        'AZ': 'Arizona',
        'CA': 'California',
        'CO': 'Colorado',
        'CT': 'Connecticut',
        'DC': 'District of Columbia',
        'DE': 'Delaware',
        'FL': 'Florida',
        'GA': 'Georgia',
        'GU': 'Guam',
        'HI': 'Hawaii',
        'IA': 'Iowa',
        'ID': 'Idaho',
        'IL': 'Illinois',
        'IN': 'Indiana',
        'KS': 'Kansas',
        'KY': 'Kentucky',
        'LA': 'Louisiana',
        'MA': 'Massachusetts',
        'MD': 'Maryland',
        'ME': 'Maine',
        'MI': 'Michigan',
        'MN': 'Minnesota',
        'MO': 'Missouri',
        'MP': 'Northern Mariana Islands',
        'MS': 'Mississippi',
        'MT': 'Montana',
        'NA': 'National',
        'NC': 'North Carolina',
        'ND': 'North Dakota',
        'NE': 'Nebraska',
        'NH': 'New Hampshire',
        'NJ': 'New Jersey',
        'NM': 'New Mexico',
        'NV': 'Nevada',
        'NY': 'New York',
        'OH': 'Ohio',
        'OK': 'Oklahoma',
        'OR': 'Oregon',
        'PA': 'Pennsylvania',
        'PR': 'Puerto Rico',
        'RI': 'Rhode Island',
        'SC': 'South Carolina',
        'SD': 'South Dakota',
        'TN': 'Tennessee',
        'TX': 'Texas',
        'UT': 'Utah',
        'VA': 'Virginia',
        'VI': 'Virgin Islands',
        'VT': 'Vermont',
        'WA': 'Washington',
        'WI': 'Wisconsin',
        'WV': 'West Virginia',
        'WY': 'Wyoming'}

In [154]:
# looping through dataframe and making list of all state names

states_list = []

for i in final['States']: 
    if i in states: 
        st = states[i]
        states_list.append(st)
        
states_list

['Alabama',
 'Alabama',
 'Alabama',
 'Alabama',
 'Alabama',
 'Alabama',
 'Alabama',
 'Alabama',
 'Alabama',
 'Alabama',
 'Alabama',
 'Alabama',
 'Alabama',
 'Alabama',
 'Alabama',
 'Alabama',
 'Alabama',
 'Alabama',
 'Alabama',
 'Alabama',
 'Alabama',
 'Alabama',
 'Alabama',
 'Alabama',
 'Alabama',
 'Alabama',
 'Alabama',
 'Alabama',
 'Alabama',
 'Alabama',
 'Alabama',
 'Alabama',
 'Alabama',
 'Alabama',
 'Alabama',
 'Alabama',
 'Alabama',
 'Alabama',
 'Alabama',
 'Alabama',
 'Alabama',
 'Alabama',
 'Alabama',
 'Alabama',
 'Alabama',
 'Alabama',
 'Alabama',
 'Alabama',
 'Alabama',
 'Alabama',
 'Alabama',
 'Alabama',
 'Alabama',
 'Alabama',
 'Alabama',
 'Alabama',
 'Alabama',
 'Alabama',
 'Alabama',
 'Alabama',
 'Alabama',
 'Alabama',
 'Alabama',
 'Alabama',
 'Alabama',
 'Alabama',
 'Alabama',
 'Alaska',
 'Arizona',
 'Arizona',
 'Arizona',
 'Arizona',
 'Arizona',
 'Arizona',
 'Arizona',
 'Arizona',
 'Kansas',
 'Arizona',
 'Kansas',
 'Arizona',
 'Arizona',
 'Arizona',
 'Arizona',
 'New Mexico',
 'Arizona',
 'New Mexico',
 'Arizona',
 'Arizona',
 'Arizona',
 'Arizona',
 'Arizona',
 'Arizona',
 'Arkansas',
 'Arkansas',
 'Arkansas',
 'Arkansas',
 'Arkansas',
 'Arkansas',
 'Arkansas',
 'Texas',
 'Arkansas',
 'Texas',
 'Arkansas',
 'Arkansas',
 'Arkansas',
 'Nevada',
 'Arkansas',
 'Nevada',
 'Arkansas',
 'Texas',
 'Arkansas',
 'Texas',
 'Arkansas',
 'Arkansas',
 'Oklahoma',
 'Arkansas',
 'Oklahoma',
 'Arkansas',
 'Arkansas',
 'Arkansas',
 'Arkansas',
 'Arkansas',
 'Arkansas',
 'Arkansas',
 'Texas',
 'Arkansas',
 'Texas',
 'Arkansas',
 'Arkansas',
 'Arkansas',
 'Arkansas',
 'Texas',
 'Arkansas',
 'Texas',
 'Arkansas',
 'Arkansas',
 'Arkansas',
 'New Mexico',
 'Oklahoma',
 'Arkansas',
 'New Mexico',
 'Oklahoma',
 'Arkansas',
 'New Mexico',
 'Oklahoma',
 'Arkansas',
 'Arkansas',
 'Arkansas',
 'Arkansas',
 'Texas',
 'Arkansas',
 'Texas',
 'Arkansas',
 'Arkansas',
 'Arkansas',
 'Oklahoma',
 'Texas',
 'Arkansas',
 'Oklahoma',
 'Texas',
 'Arkansas',
 'Oklahoma',
 'Texas',
 'Arkansas',
 'Oklahoma',
 'Texas',
 'Arkansas',
 'Oklahoma',
 'Texas',
 'Arkansas',
 'Oklahoma',
 'Texas',
 'Arkansas',
 'Texas',
 'Arkansas',
 'Texas',
 'Arkansas',
 'Arkansas',
 'Arkansas',
 'Texas',
 'Arkansas',
 'Texas',
 'Arkansas',
 'Nevada',
 'New Mexico',
 'Oklahoma',
 'Arkansas',
 'Nevada',
 'New Mexico',
 'Oklahoma',
 'Arkansas',
 'Nevada',
 'New Mexico',
 'Oklahoma',
 'Arkansas',
 'Nevada',
 'New Mexico',
 'Oklahoma',
 'Arkansas',
 'Arkansas',
 'Oklahoma',
 'Arkansas',
 'Oklahoma',
 'Arkansas',
 'Arkansas',
 'Texas',
 'Arkansas',
 'Texas',
 'Arkansas',
 'Texas',
 'Arkansas',
 'Texas',
 'Arkansas',
 'Arkansas',
 'Arkansas',
 'Arkansas',
 'Texas',
 'Arkansas',
 'Texas',
 'Arkansas',
 'Arkansas',
 'Texas',
 'Arkansas',
 'Texas',
 'Arkansas',
 'Arkansas',
 'Arkansas',
 'Arkansas',
 'Arkansas',
 'Arkansas',
 'Texas',
 'Arkansas',
 'Texas',
 'Arkansas',
 'Arkansas',
 'Arkansas',
 'Arkansas',
 'Arkansas',
 'Arkansas',
 'Arkansas',
 'Arkansas',
 'Arkansas',
 'Arkansas',
 'Arkansas',
 'Arkansas',
 'Arkansas',
 'New Mexico',
 'Arkansas',
 'New Mexico',
 'Arkansas',
 'Arkansas',
 'Oklahoma',
 'Texas',
 'Arkansas',
 'Oklahoma',
 'Texas',
 'Arkansas',
 'Oklahoma',
 'Texas',
 'Arkansas',
 'Arkansas',
 'Arkansas',
 'Arkansas',
 'Arkansas',
 'California',
 'California',
 'California',
 'California',
 'California',
 'California',
 'California',
 'California',
 'California',
 'California',
 'California',
 'California',
 'California',
 'California',
 'California',
 'California',
 'California',
 'California',
 'California',
 'California',
 'California',
 'California',
 'California',
 'California',
 'California',
 'California',
 'California',
 'California',
 'California',
 'California',
 'California',
 'California',
 'California',
 'California',
 'California',
 'California',
 'California',
 'California',
 'California',
 'California',
 'California',
 'California',
 'California',
 'California',
 'California',
 'California',
 'California',
 'California',
 'California',
 'California',
 'California',
 'California',
 'California',
 'California',
 'California',
 'California',
 'California',
 'California',
 'Colorado',
 'Colorado',
 'Colorado',
 'Colorado',
 'Colorado',
 'Colorado',
 'Colorado',
 'Colorado',
 'Colorado',
 'Colorado',
 'Colorado',
 'Colorado',
 'Colorado',
 'Michigan',
 'Colorado',
 'Michigan',
 'Colorado',
 'Colorado',
 'Colorado',
 'Illinois',
 'Kansas',
 'Colorado',
 'Illinois',
 'Kansas',
 'Colorado',
 'Illinois',
 'Kansas',
 'Colorado',
 'Colorado',
 'Colorado',
 'Colorado',
 'Colorado',
 'Colorado',
 'Colorado',
 'Colorado',
 'Colorado',
 'Colorado',
 'Colorado',
 'Georgia',
 'Illinois',
 'Kansas',
 'Kentucky',
 'North Carolina',
 'Tennessee',
 'Colorado',
 'Georgia',
 'Illinois',
 'Kansas',
 'Kentucky',
 'North Carolina',
 'Tennessee',
 'Colorado',
 'Georgia',
 'Illinois',
 'Kansas',
 'Kentucky',
 'North Carolina',
 'Tennessee',
 'Colorado',
 'Georgia',
 'Illinois',
 'Kansas',
 'Kentucky',
 'North Carolina',
 'Tennessee',
 'Colorado',
 'Georgia',
 'Illinois',
 'Kansas',
 'Kentucky',
 'North Carolina',
 'Tennessee',
 'Colorado',
 'Georgia',
 'Illinois',
 'Kansas',
 'Kentucky',
 'North Carolina',
 'Tennessee',
 'Colorado',
 'Georgia',
 'Illinois',
 'Kansas',
 'Kentucky',
 'North Carolina',
 'Tennessee',
 'Colorado',
 'Wisconsin',
 'Colorado',
 'Wisconsin',
 'Colorado',
 'Colorado',
 'Colorado',
 'Michigan',
 'Colorado',
 'Michigan',
 'Colorado',
 'Colorado',
 'Colorado',
 'Colorado',
 'Wisconsin',
 'Colorado',
 'Wisconsin',
 'Colorado',
 'Colorado',
 'Colorado',
 'Colorado',
 'Colorado',
 'Colorado',
 'Colorado',
 'Colorado',
 'Colorado',
 'Colorado',
 'Colorado',
 'Colorado',
 'Colorado',
 'Colorado',
 'Colorado',
 'Colorado',
 'Colorado',
 'Colorado',
 'Colorado',
 'Colorado',
 'Colorado',
 'Colorado',
 'Colorado',
 'Colorado',
 'North Carolina',
 'Wisconsin',
 'Colorado',
 'North Carolina',
 'Wisconsin',
 'Colorado',
 'North Carolina',
 'Wisconsin',
 'Colorado',
 'Colorado',
 'Colorado',
 'Wisconsin',
 'Colorado',
 'Wisconsin',
 'Colorado',
 'Colorado',
 'Connecticut',
 'Delaware',
 'Delaware',
 'Delaware',
 'District of Columbia',
 'Florida',
 'Florida',
 'Florida',
 'Florida',
 'Florida',
 'Florida',
 'Florida',
 'Florida',
 'Florida',
 'Florida',
 'Florida',
 'Florida',
 'Florida',
 'Florida',
 'Florida',
 'Florida',
 'Florida',
 'Florida',
 'Florida',
 'Florida',
 'Florida',
 'Florida',
 'Florida',
 'Florida',
 'Florida',
 'Florida',
 'Florida',
 'Florida',
 'Florida',
 'Florida',
 'Florida',
 'Florida',
 'Florida',
 'Florida',
 'Florida',
 'Florida',
 'Florida',
 'Florida',
 'Florida',
 'Florida',
 'Florida',
 'Florida',
 'Florida',
 'Florida',
 'Florida',
 'Florida',
 'Florida',
 'Florida',
 'Florida',
 'Florida',
 'Florida',
 'Florida',
 'Florida',
 'Florida',
 'Florida',
 'Florida',
 'Florida',
 'Florida',
 'Florida',
 'Florida',
 'Florida',
 'Florida',
 'Florida',
 'Florida',
 'Florida',
 'Florida',
 'Georgia',
 'Georgia',
 'Georgia',
 'Georgia',
 'Georgia',
 'Georgia',
 'Georgia',
 'Georgia',
 'Georgia',
 'Georgia',
 'Georgia',
 'Georgia',
 'Georgia',
 'Georgia',
 'Georgia',
 'Georgia',
 'Georgia',
 'North Carolina',
 'Georgia',
 'North Carolina',
 'Georgia',
 'Georgia',
 'Georgia',
 'New Jersey',
 'North Carolina',
 'Georgia',
 'New Jersey',
 'North Carolina',
 'Georgia',
 'New Jersey',
 'North Carolina',
 'Georgia',
 'Georgia',
 'Illinois',
 'Kentucky',
 'Tennessee',
 'Georgia',
 'Illinois',
 'Kentucky',
 'Tennessee',
 'Georgia',
 'Illinois',
 'Kentucky',
 'Tennessee',
 'Georgia',
 'Illinois',
 'Kentucky',
 'Tennessee',
 'Georgia',
 'Georgia',
 'Georgia',
 'North Carolina',
 'Georgia',
 'North Carolina',
 'Georgia',
 'Georgia',
 'Georgia',
 'Kansas',
 'North Carolina',
 'Georgia',
 'Kansas',
 'North Carolina',
 'Georgia',
 'Kansas',
 'North Carolina',
 'Georgia',
 'Georgia',
 'Georgia',
 'Georgia',
 'Georgia',
 'Georgia',
 'Tennessee',
 'Georgia',
 'Tennessee',
 'Georgia',
 'Georgia',
 'Georgia',
 'Georgia',
 'Georgia',
 'Illinois',
 'Kansas',
 'Georgia',
 'Illinois',
 'Kansas',
 'Georgia',
 'Illinois',
 'Kansas',
 'Georgia',
 'Georgia',
 'Georgia',
 'Georgia',
 'Georgia',
 'Georgia',
 'Georgia',
 'Georgia',
 'Georgia',
 'Georgia',
 'Georgia',
 'Georgia',
 'Georgia',
 'Georgia',
 'Georgia',
 'Georgia',
 'Georgia',
 'Illinois',
 'Kentucky',
 'Tennessee',
 'Georgia',
 'Illinois',
 'Kentucky',
 'Tennessee',
 'Georgia',
 'Illinois',
 'Kentucky',
 'Tennessee',
 'Georgia',
 'Illinois',
 'Kentucky',
 'Tennessee',
 'Georgia',
 'Kentucky',
 'Georgia',
 'Kentucky',
 'Georgia',
 'North Carolina',
 'Georgia',
 'North Carolina',
 'Georgia',
 'Illinois',
 'Kansas',
 'Kentucky',
 'North Carolina',
 'Tennessee',
 'Georgia',
 'Illinois',
 'Kansas',
 'Kentucky',
 'North Carolina',
 'Tennessee',
 'Georgia',
 'Illinois',
 'Kansas',
 'Kentucky',
 'North Carolina',
 'Tennessee',
 'Georgia',
 'Illinois',
 'Kansas',
 'Kentucky',
 'North Carolina',
 'Tennessee',
 'Georgia',
 'Illinois',
 'Kansas',
 'Kentucky',
 'North Carolina',
 'Tennessee',
 'Georgia',
 'Illinois',
 'Kansas',
 'Kentucky',
 'North Carolina',
 'Tennessee',
 'Georgia',
 'Georgia',
 'Georgia',
 'Georgia',
 'Georgia',
 'Georgia',
 'Georgia',
 'Illinois',
 'North Carolina',
 'Tennessee',
 'Georgia',
 'Illinois',
 'North Carolina',
 'Tennessee',
 'Georgia',
 'Illinois',
 'North Carolina',
 'Tennessee',
 'Georgia',
 'Illinois',
 'North Carolina',
 'Tennessee',
 'Georgia',
 'Georgia',
 'Georgia',
 'Georgia',
 'Illinois',
 'Kentucky',
 'Tennessee',
 'Georgia',
 'Illinois',
 'Kentucky',
 'Tennessee',
 'Georgia',
 'Illinois',
 'Kentucky',
 'Tennessee',
 'Georgia',
 'Illinois',
 'Kentucky',
 'Tennessee',
 'Georgia',
 'Georgia',
 'Georgia',
 'Kentucky',
 'Georgia',
 'Kentucky',
 'Georgia',
 'Georgia',
 'Illinois',
 'Kentucky',
 'Tennessee',
 'Georgia',
 'Illinois',
 'Kentucky',
 'Tennessee',
 'Georgia',
 'Illinois',
 'Kentucky',
 'Tennessee',
 'Georgia',
 'Illinois',
 'Kentucky',
 'Tennessee',
 'Georgia',
 'Georgia',
 'Georgia',
 'Georgia',
 'Georgia',
 'Illinois',
 'Kansas',
 'Kentucky',
 'Tennessee',
 'Georgia',
 'Illinois',
 'Kansas',
 'Kentucky',
 'Tennessee',
 'Georgia',
 'Illinois',
 'Kansas',
 'Kentucky',
 'Tennessee',
 'Georgia',
 'Illinois',
 'Kansas',
 'Kentucky',
 'Tennessee',
 'Georgia',
 'Illinois',
 'Kansas',
 'Kentucky',
 'Tennessee',
 'Georgia',
 'Georgia',
 'Georgia',
 'Georgia',
 'Georgia',
 'Georgia',
 'Georgia',
 'Illinois',
 'Kentucky',
 'Georgia',
 'Illinois',
 'Kentucky',
 'Georgia',
 'Illinois',
 'Kentucky',
 'Georgia',
 'Georgia',
 'Georgia',
 'Georgia',
 'Georgia',
 'Georgia',
 'Georgia',
 'Georgia',
 'Georgia',
 'Georgia',
 'Georgia',
 'Georgia',
 'Georgia',
 'Kansas',
 'North Carolina',
 'Georgia',
 'Kansas',
 'North Carolina',
 'Georgia',
 'Kansas',
 'North Carolina',
 'Georgia',
 'Georgia',
 'Illinois',
 'Kansas',
 'Kentucky',
 'Tennessee',
 'Georgia',
 'Illinois',
 'Kansas',
 'Kentucky',
 'Tennessee',
 'Georgia',
 'Illinois',
 'Kansas',
 'Kentucky',
 'Tennessee',
 'Georgia',
 'Illinois',
 'Kansas',
 'Kentucky',
 'Tennessee',
 'Georgia',
 'Illinois',
 'Kansas',
 'Kentucky',
 'Tennessee',
 'Georgia',
 'Illinois',
 'Kentucky',
 'Tennessee',
 'Georgia',
 'Illinois',
 'Kentucky',
 'Tennessee',
 'Georgia',
 'Illinois',
 'Kentucky',
 'Tennessee',
 'Georgia',
 'Illinois',
 'Kentucky',
 'Tennessee',
 'Georgia',
 'Georgia',
 'Georgia',
 'Georgia',
 'Georgia',
 'Georgia',
 'Georgia',
 'Georgia',
 'Georgia',
 'Georgia',
 'Illinois',
 'Kentucky',
 'Georgia',
 'Illinois',
 'Kentucky',
 'Georgia',
 'Illinois',
 'Kentucky',
 'Georgia',
 'Georgia',
 'Illinois',
 'Kentucky',
 'Georgia',
 'Illinois',
 'Kentucky',
 'Georgia',
 'Illinois',
 'Kentucky',
 'Georgia',
 'Georgia',
 'Georgia',
 'Georgia',
 'Georgia',
 'Georgia',
 'Georgia',
 'Georgia',
 'Georgia',
 'Georgia',
 'Georgia',
 'Georgia',
 'Georgia',
 'Georgia',
 'Georgia',
 'Georgia',
 'Georgia',
 'Georgia',
 'Georgia',
 'Georgia',
 'Georgia',
 'Georgia',
 'Georgia',
 'Georgia',
 'Georgia',
 'Georgia',
 'Georgia',
 'Georgia',
 'Georgia',
 'Georgia',
 'Georgia',
 'Georgia',
 'Georgia',
 'Georgia',
 'Illinois',
 'Kansas',
 'Kentucky',
 'Tennessee',
 'Georgia',
 'Illinois',
 'Kansas',
 'Kentucky',
 'Tennessee',
 'Georgia',
 'Illinois',
 'Kansas',
 'Kentucky',
 'Tennessee',
 'Georgia',
 'Illinois',
 'Kansas',
 'Kentucky',
 'Tennessee',
 'Georgia',
 'Illinois',
 'Kansas',
 'Kentucky',
 'Tennessee',
 'Georgia',
 'Illinois',
 'Kentucky',
 'North Carolina',
 'Tennessee',
 'Georgia',
 'Illinois',
 'Kentucky',
 'North Carolina',
 'Tennessee',
 'Georgia',
 'Illinois',
 'Kentucky',
 'North Carolina',
 'Tennessee',
 'Georgia',
 'Illinois',
 'Kentucky',
 'North Carolina',
 'Tennessee',
 'Georgia',
 'Illinois',
 'Kentucky',
 'North Carolina',
 'Tennessee',
 'Georgia',
 'Kentucky',
 'Georgia',
 'Kentucky',
 'Georgia',
 'Georgia',
 'Georgia',
 'Georgia',
 'Georgia',
 'North Carolina',
 'Georgia',
 'North Carolina',
 'Georgia',
 'Georgia',
 'Guam',
 'Hawaii',
 'Hawaii',
 'Hawaii',
 'Hawaii',
 ...]

In [155]:
# making Full State Name column in dataframe to hold full state names 
# dropping old States column that had only the state abbreviations

final['Full State Name'] = states_list
final = final.drop(columns=['States'])
final

                    Counties Total SNAP Full State Name
0          AUTAUGA CO FS OFF      14105         Alabama
1          BALDWIN CO FS OFF      37409         Alabama
2          BARBOUR CO FS OFF      11984         Alabama
3             BIBB CO FS OFF       7648         Alabama
4           BLOUNT CO FS OFF      16461         Alabama
5          BULLOCK CO FS OFF       5629         Alabama
6              BUTLER CO FSO      10171         Alabama
7          CALHOUN CO FS OFF      47333         Alabama
8         CHAMBERS CO FS OFF      15914         Alabama
9      CHEROKEE CO FS OFFICE      10011         Alabama
10         CHILTON CO FS OFF      18489         Alabama
11         CHOCTAW CO FS OFF       6344         Alabama
12         CLARKE CO FS OFF.      11854         Alabama
13            CLAY CO FS OFF       4177         Alabama
14        CLEBURNE CO FS OFF       4805         Alabama
15          COFFEE CO FS OFF      11586         Alabama
16         COLBERT CO FS OFF      17488         Alabama
17         CONECUH CO FS OFF       8297         Alabama
18              COOSA CO FSO       3941         Alabama
19       COVINGTON CO FS OFF      15241         Alabama
20           CRENSHAW CO FSO       5686         Alabama
21         CULLMAN CO FS OFF      21887         Alabama
22            DALE CO FS OFF      19726         Alabama
23          DALLAS CO FS OFF      32665         Alabama
24          DEKALB CO FS OFF      24959         Alabama
25          ELMORE CO FS OFF      21225         Alabama
26        ESCAMBIA CO FS OFF      18043         Alabama
27          ETOWQH CO FS OFF      33315         Alabama
28         FAYETTE CO FS OFF       7404         Alabama
29        FRANKLIN CO FS OFF      12350         Alabama
...                      ...        ...             ...
3414          PORTAGE CO DSS      12327       Wisconsin
3415            PRICE CO DSS       3730       Wisconsin
3416           RACINE CO DSS      57114       Wisconsin
3417         RICHLAND CO DSS       5110       Wisconsin
3418             ROCK CO DSS      50776       Wisconsin
3419             RUSK CO DSS       5335       Wisconsin
3420         ST CROIX CO DSS      10887       Wisconsin
3421             SAUK CO DSS      12835       Wisconsin
3422           SAWYER CO DSS       6360       Wisconsin
3423          SHAWANO CO DSS       8766       Wisconsin
3424        SHEBOYGAN CO DSS      24034       Wisconsin
3425           TAYLOR CO DSS       4844       Wisconsin
3426      TREMPEALEAU CO DSS       5762       Wisconsin
3427           VERNON CO DSS       5760       Wisconsin
3428            VILAS CO DSS       3744       Wisconsin
3429         WALWORTH CO DSS      21095       Wisconsin
3430         WASHBURN CO DSS       5214       Wisconsin
3431         WAUKESHA CO DSS      28157       Wisconsin
3432          WAUPACA CO DSS      10141       Wisconsin
3433         WAUSHARA CO DSS       5947       Wisconsin
3434        WINNEBAGO CO DSS      30220       Wisconsin
3435             WOOD CO DSS      18757       Wisconsin
3436   ONEIDA TRIBAL COUNCIL       4818       Wisconsin
3437  STOCKBRIDGE-MUNSEE TRI        458       Wisconsin
3438  RED CLIFF TRIBAL COUNC       1215       Wisconsin
3439  BAD RIVER TRIBAL COUNC       1078       Wisconsin
3440  LAC DU FLAMBEAU TRIBAL       2718       Wisconsin
3441  SOKAOGON TRIBAL AGENCY        458       Wisconsin
3442        POTAWATOMI TRIBE        144       Wisconsin
3443         WYOMING SD PASS      69813         Wyoming

[3444 rows x 3 columns]

In [156]:
# cleaning up the county names so that I can match them with the counties we have in the life expectancy dataframe

output = []
for i in final['Counties']:
    just_county_name = i.split(' CO ')[:1]
    output.extend(just_county_name)
    
final['Split Counties'] = output

final = final.drop(columns=['Counties'])
final

     Total SNAP Full State Name          Split Counties
0         14105         Alabama                 AUTAUGA
1         37409         Alabama                 BALDWIN
2         11984         Alabama                 BARBOUR
3          7648         Alabama                    BIBB
4         16461         Alabama                  BLOUNT
5          5629         Alabama                 BULLOCK
6         10171         Alabama                  BUTLER
7         47333         Alabama                 CALHOUN
8         15914         Alabama                CHAMBERS
9         10011         Alabama                CHEROKEE
10        18489         Alabama                 CHILTON
11         6344         Alabama                 CHOCTAW
12        11854         Alabama                  CLARKE
13         4177         Alabama                    CLAY
14         4805         Alabama                CLEBURNE
15        11586         Alabama                  COFFEE
16        17488         Alabama                 COLBERT
17         8297         Alabama                 CONECUH
18         3941         Alabama                   COOSA
19        15241         Alabama               COVINGTON
20         5686         Alabama                CRENSHAW
21        21887         Alabama                 CULLMAN
22        19726         Alabama                    DALE
23        32665         Alabama                  DALLAS
24        24959         Alabama                  DEKALB
25        21225         Alabama                  ELMORE
26        18043         Alabama                ESCAMBIA
27        33315         Alabama                  ETOWQH
28         7404         Alabama                 FAYETTE
29        12350         Alabama                FRANKLIN
...         ...             ...                     ...
3414      12327       Wisconsin                 PORTAGE
3415       3730       Wisconsin                   PRICE
3416      57114       Wisconsin                  RACINE
3417       5110       Wisconsin                RICHLAND
3418      50776       Wisconsin                    ROCK
3419       5335       Wisconsin                    RUSK
3420      10887       Wisconsin                ST CROIX
3421      12835       Wisconsin                    SAUK
3422       6360       Wisconsin                  SAWYER
3423       8766       Wisconsin                 SHAWANO
3424      24034       Wisconsin               SHEBOYGAN
3425       4844       Wisconsin                  TAYLOR
3426       5762       Wisconsin             TREMPEALEAU
3427       5760       Wisconsin                  VERNON
3428       3744       Wisconsin                   VILAS
3429      21095       Wisconsin                WALWORTH
3430       5214       Wisconsin                WASHBURN
3431      28157       Wisconsin                WAUKESHA
3432      10141       Wisconsin                 WAUPACA
3433       5947       Wisconsin                WAUSHARA
3434      30220       Wisconsin               WINNEBAGO
3435      18757       Wisconsin                    WOOD
3436       4818       Wisconsin   ONEIDA TRIBAL COUNCIL
3437        458       Wisconsin  STOCKBRIDGE-MUNSEE TRI
3438       1215       Wisconsin  RED CLIFF TRIBAL COUNC
3439       1078       Wisconsin  BAD RIVER TRIBAL COUNC
3440       2718       Wisconsin  LAC DU FLAMBEAU TRIBAL
3441        458       Wisconsin  SOKAOGON TRIBAL AGENCY
3442        144       Wisconsin        POTAWATOMI TRIBE
3443      69813         Wyoming         WYOMING SD PASS

[3444 rows x 3 columns]

In [157]:
# importing/cleaning life expectancy csv in order to get list of counties we're working with

counties = pd.read_csv('/Users/flatironschool/Flatiron_Projects/life-expectancy/new_copy_of_repo/module_two_project/csv_files/life_expectancy_data_county.csv', header=None)
counties = counties.rename(columns={0:'Counties', 1:'State', 2: 'Life Expectancy'})
counties = counties.drop(counties.index[0])

# turning all county names in county dataframe uppercase so that they match the SNAP dataframe for easier pairing
counties['Uppercase Counties'] = [i.upper() for i in counties['Counties']]

# resetting index to start at 0
counties = counties.reset_index(drop=True)

# looping through SNAP dataframe and creating list of all full county names from counties dataframe
counties_list = []
for i in range(0,len(final['Split Counties'])):
    if i in counties['Uppercase Counties']:
        counties_list.append(counties['Counties'][i])
    else: 
        counties_list.append('False')

# making new column in SNAP dataframe for full county names, which I took from the counties dataframe via the for-loop above
final['Proper Counties'] = counties_list

# dropping Split Counties column from SNAP dataframe
final = final.drop(columns=['Split Counties'])


# FOR SOME REASON THERE ARE NOW NO WISCONSIN COUNTIES IN SNAP DATAFRAME EVEN THOUGH MY CODE SHOULD HAVE MATCHED MANY BETWEEN THE COUNTIES DATAFRAME AND THE SNAP DATAFRAME
## HELP HERE PLEASE ##

     Total SNAP Full State Name   Proper Counties
0         14105         Alabama    Autauga County
1         37409         Alabama    Baldwin County
2         11984         Alabama    Barbour County
3          7648         Alabama       Bibb County
4         16461         Alabama     Blount County
5          5629         Alabama    Bullock County
6         10171         Alabama     Butler County
7         47333         Alabama    Calhoun County
8         15914         Alabama   Chambers County
9         10011         Alabama   Cherokee County
10        18489         Alabama    Chilton County
11         6344         Alabama    Choctaw County
12        11854         Alabama     Clarke County
13         4177         Alabama       Clay County
14         4805         Alabama   Cleburne County
15        11586         Alabama     Coffee County
16        17488         Alabama    Colbert County
17         8297         Alabama    Conecuh County
18         3941         Alabama      Coosa County
19        15241         Alabama  Covington County
20         5686         Alabama   Crenshaw County
21        21887         Alabama    Cullman County
22        19726         Alabama       Dale County
23        32665         Alabama     Dallas County
24        24959         Alabama     DeKalb County
25        21225         Alabama     Elmore County
26        18043         Alabama   Escambia County
27        33315         Alabama     Etowah County
28         7404         Alabama    Fayette County
29        12350         Alabama   Franklin County
...         ...             ...               ...
3414      12327       Wisconsin             False
3415       3730       Wisconsin             False
3416      57114       Wisconsin             False
3417       5110       Wisconsin             False
3418      50776       Wisconsin             False
3419       5335       Wisconsin             False
3420      10887       Wisconsin             False
3421      12835       Wisconsin             False
3422       6360       Wisconsin             False
3423       8766       Wisconsin             False
3424      24034       Wisconsin             False
3425       4844       Wisconsin             False
3426       5762       Wisconsin             False
3427       5760       Wisconsin             False
3428       3744       Wisconsin             False
3429      21095       Wisconsin             False
3430       5214       Wisconsin             False
3431      28157       Wisconsin             False
3432      10141       Wisconsin             False
3433       5947       Wisconsin             False
3434      30220       Wisconsin             False
3435      18757       Wisconsin             False
3436       4818       Wisconsin             False
3437        458       Wisconsin             False
3438       1215       Wisconsin             False
3439       1078       Wisconsin             False
3440       2718       Wisconsin             False
3441        458       Wisconsin             False
3442        144       Wisconsin             False
3443      69813         Wyoming             False

[3444 rows x 3 columns]

In [160]:
counties

                Counties       State Life Expectancy  Uppercase Counties
0         Autauga County     Alabama           75.74      AUTAUGA COUNTY
1         Baldwin County     Alabama           77.80      BALDWIN COUNTY
2         Barbour County     Alabama           75.34      BARBOUR COUNTY
3            Bibb County     Alabama           74.13         BIBB COUNTY
4          Blount County     Alabama           76.41       BLOUNT COUNTY
5         Bullock County     Alabama           73.61      BULLOCK COUNTY
6          Butler County     Alabama           73.63       BUTLER COUNTY
7         Calhoun County     Alabama           74.11      CALHOUN COUNTY
8        Chambers County     Alabama           74.09     CHAMBERS COUNTY
9        Cherokee County     Alabama           75.26     CHEROKEE COUNTY
10        Chilton County     Alabama           74.50      CHILTON COUNTY
11        Choctaw County     Alabama           75.19      CHOCTAW COUNTY
12         Clarke County     Alabama           75.29       CLARKE COUNTY
13           Clay County     Alabama           75.25         CLAY COUNTY
14       Cleburne County     Alabama           74.53     CLEBURNE COUNTY
15         Coffee County     Alabama           76.50       COFFEE COUNTY
16        Colbert County     Alabama           75.26      COLBERT COUNTY
17        Conecuh County     Alabama           74.08      CONECUH COUNTY
18          Coosa County     Alabama           75.21        COOSA COUNTY
19      Covington County     Alabama           75.42    COVINGTON COUNTY
20       Crenshaw County     Alabama           74.47     CRENSHAW COUNTY
21        Cullman County     Alabama           75.48      CULLMAN COUNTY
22           Dale County     Alabama           76.33         DALE COUNTY
23         Dallas County     Alabama           72.48       DALLAS COUNTY
24         DeKalb County     Alabama           75.33       DEKALB COUNTY
25         Elmore County     Alabama           75.95       ELMORE COUNTY
26       Escambia County     Alabama           74.30     ESCAMBIA COUNTY
27         Etowah County     Alabama           73.86       ETOWAH COUNTY
28        Fayette County     Alabama           74.26      FAYETTE COUNTY
29       Franklin County     Alabama           73.57     FRANKLIN COUNTY
...                  ...         ...             ...                 ...
3112     Washburn County   Wisconsin           78.32     WASHBURN COUNTY
3113   Washington County   Wisconsin           80.97   WASHINGTON COUNTY
3114     Waukesha County   Wisconsin           81.31     WAUKESHA COUNTY
3115      Waupaca County   Wisconsin           77.88      WAUPACA COUNTY
3116     Waushara County   Wisconsin           79.12     WAUSHARA COUNTY
3117    Winnebago County   Wisconsin           79.99    WINNEBAGO COUNTY
3118         Wood County   Wisconsin           80.46         WOOD COUNTY
3119       Albany County     Wyoming           80.31       ALBANY COUNTY
3120     Big Horn County     Wyoming           77.78     BIG HORN COUNTY
3121     Campbell County     Wyoming           77.41     CAMPBELL COUNTY
3122       Carbon County     Wyoming           77.34       CARBON COUNTY
3123     Converse County     Wyoming           78.68     CONVERSE COUNTY
3124        Crook County     Wyoming           79.76        CROOK COUNTY
3125      Fremont County     Wyoming           75.74      FREMONT COUNTY
3126       Goshen County     Wyoming           79.64       GOSHEN COUNTY
3127  Hot Springs County     Wyoming           77.24  HOT SPRINGS COUNTY
3128      Johnson County     Wyoming           79.35      JOHNSON COUNTY
3129      Laramie County     Wyoming           78.51      LARAMIE COUNTY
3130      Lincoln County     Wyoming           79.83      LINCOLN COUNTY
3131      Natrona County     Wyoming           77.75      NATRONA COUNTY
3132     Niobrara County     Wyoming           78.63     NIOBRARA COUNTY
3133         Park County     Wyoming           79.99         PARK COUNTY
3134       Platte County     Wyoming           78.67       PLATTE COUNTY
3135     Sheridan County     Wyoming           78.36     SHERIDAN COUNTY
3136     Sublette County     Wyoming           80.29     SUBLETTE COUNTY
3137   Sweetwater County     Wyoming           77.93   SWEETWATER COUNTY
3138        Teton County     Wyoming           82.95        TETON COUNTY
3139        Uinta County     Wyoming           77.51        UINTA COUNTY
3140     Washakie County     Wyoming           78.77     WASHAKIE COUNTY
3141       Weston County     Wyoming           78.64       WESTON COUNTY

[3142 rows x 4 columns]

In [159]:
# filtering out all rows where Proper Counties = False
final[final['Proper Counties'] != 'False']

     Total SNAP Full State Name     Proper Counties
0         14105         Alabama      Autauga County
1         37409         Alabama      Baldwin County
2         11984         Alabama      Barbour County
3          7648         Alabama         Bibb County
4         16461         Alabama       Blount County
5          5629         Alabama      Bullock County
6         10171         Alabama       Butler County
7         47333         Alabama      Calhoun County
8         15914         Alabama     Chambers County
9         10011         Alabama     Cherokee County
10        18489         Alabama      Chilton County
11         6344         Alabama      Choctaw County
12        11854         Alabama       Clarke County
13         4177         Alabama         Clay County
14         4805         Alabama     Cleburne County
15        11586         Alabama       Coffee County
16        17488         Alabama      Colbert County
17         8297         Alabama      Conecuh County
18         3941         Alabama        Coosa County
19        15241         Alabama    Covington County
20         5686         Alabama     Crenshaw County
21        21887         Alabama      Cullman County
22        19726         Alabama         Dale County
23        32665         Alabama       Dallas County
24        24959         Alabama       DeKalb County
25        21225         Alabama       Elmore County
26        18043         Alabama     Escambia County
27        33315         Alabama       Etowah County
28         7404         Alabama      Fayette County
29        12350         Alabama     Franklin County
...         ...             ...                 ...
3112      14380           Texas     Washburn County
3113        238           Texas   Washington County
3114       3392           Texas     Waukesha County
3115      19911           Texas      Waupaca County
3116       1210           Texas     Waushara County
3117       5707           Texas    Winnebago County
3118      27175           Texas         Wood County
3119       3713           Texas       Albany County
3120        115           Texas     Big Horn County
3121         71           Texas     Campbell County
3122      11542           Texas       Carbon County
3123        971           Texas     Converse County
3124          8           Texas        Crook County
3125       1156           Texas      Fremont County
3126      13804           Texas       Goshen County
3127       1357           Texas  Hot Springs County
3128      19021           Texas      Johnson County
3129       5602           Texas      Laramie County
3130       5539           Texas      Lincoln County
3131       3310           Texas      Natrona County
3132       3972           Texas     Niobrara County
3133       4211           Texas         Park County
3134      26545           Texas       Platte County
3135       7528           Texas     Sheridan County
3136        531           Texas     Sublette County
3137       2909           Texas   Sweetwater County
3138       4267           Texas        Teton County
3139          3           Texas        Uinta County
3140      82400           Texas     Washakie County
3141       2182           Texas       Weston County

[3142 rows x 3 columns]

In [ ]:
## OLD CODE - HAVEN'T TOUCHED ##

In [145]:
# making new col named 'Full States' to store full state names
final_frame['Full States'] = states_list


# Deleting old column names 'States'
final_frame.drop(columns=['States'])

# # Merging 'Counties' & 'Full States'
final_frame['CountyState'] = final_frame['Counties'].map(str) + " " + final_frame['Full States']


# # Deleting old 'Counties' and 'Full States' cols
final_final = final_frame.drop(columns=['Counties', 'Full States'])

,States,Jan & July Public Assist. Participation,Jan & July Non-Public Assist. Participation,Jan & July TOTAL Assist. Participation,Counties,Full States,CountyState
0,AL,1706,12399,14105,Autauga County,Alabama,Autauga County Alabama
1,AL,3236,34173,37409,Baldwin County,Alabama,Baldwin County Alabama
2,AL,2137,9847,11984,Barbour County,Alabama,Barbour County Alabama
3,AL,1195,6453,7648,Bibb County,Alabama,Bibb County Alabama
4,AL,2046,14415,16461,Blount County,Alabama,Blount County Alabama
5,AL,1189,4440,5629,Bullock County,Alabama,Bullock County Alabama
6,AL,1766,8405,10171,Butler County,Alabama,Butler County Alabama
7,AL,7206,40127,47333,Calhoun County,Alabama,Calhoun County Alabama
8,AL,2509,13405,15914,Chambers County,Alabama,Chambers County Alabama
9,AL,1422,8589,10011,Cherokee County,Alabama,Cherokee County Alabama
10,AL,2271,16218,18489,Chilton County,Alabama,Chilton County Alabama
11,AL,1005,5339,6344,Choctaw County,Alabama,Choctaw County Alabama
12,AL,2381,9473,11854,Clarke County,Alabama,Clarke County Alabama
13,AL,567,3610,4177,Clay County,Alabama,Clay County Alabama
14,AL,626,4179,4805,Cleburne County,Alabama,Cleburne County Alabama
15,AL,1426,10160,11586,Coffee County,Alabama,Coffee County Alabama
16,AL,2359,15129,17488,Colbert County,Alabama,Colbert County Alabama
17,AL,1284,7013,8297,Conecuh County,Alabama,Conecuh County Alabama
18,AL,582,3359,3941,Coosa County,Alabama,Coosa County Alabama
19,AL,1832,13409,15241,Covington County,Alabama,Covington County Alabama
20,AL,945,4741,5686,Crenshaw County,Alabama,Crenshaw County Alabama
21,AL,2769,19118,21887,Cullman County,Alabama,Cullman County Alabama
22,AL,3104,16622,19726,Dale County,Alabama,Dale County Alabama
23,AL,6924,25741,32665,Dallas County,Alabama,Dallas County Alabama
24,AL,2455,22504,24959,DeKalb County,Alabama,DeKalb County Alabama
25,AL,2848,18377,21225,Elmore County,Alabama,Elmore County Alabama
26,AL,2245,15798,18043,Escambia County,Alabama,Escambia County Alabama
27,AL,4446,28869,33315,Etowah County,Alabama,Etowah County Alabama
28,AL,1427,5977,7404,Fayette County,Alabama,Fayette County Alabama
29,AL,1656,10694,12350,Franklin County,Alabama,Franklin County Alabama
...,...,...,...,...,...,...,...
3106,TX,257,8383,8640,Washburn County,Texas,Washburn County Texas
3107,TX,15,1298,1313,Washington County,Texas,Washington County Texas
3108,TX,264,23250,23514,Waukesha County,Texas,Waukesha County Texas
3109,TX,81,5026,5107,Waupaca County,Texas,Waupaca County Texas
3110,TX,6,164,170,Waushara County,Texas,Waushara County Texas
3111,TX,7,963,970,Winnebago County,Texas,Winnebago County Texas
3112,TX,142,14238,14380,Wood County,Texas,Wood County Texas
3113,TX,10,228,238,Albany County,Texas,Albany County Texas
3114,TX,28,3364,3392,Big Horn County,Texas,Big Horn County Texas
3115,TX,380,19531,19911,Campbell County,Texas,Campbell County Texas
3116,TX,23,1187,1210,Carbon County,Texas,Carbon County Texas
3117,TX,54,5653,5707,Converse County,Texas,Converse County Texas
3118,TX,484,26691,27175,Crook County,Texas,Crook County Texas
3119,TX,25,3688,3713,Fremont County,Texas,Fremont County Texas
3120,TX,3,112,115,Goshen County,Texas,Goshen County Texas
3121,TX,0,71,71,Hot Springs County,Texas,Hot Springs County Texas
3122,TX,87,11455,11542,Johnson County,Texas,Johnson County Texas
3123,TX,8,963,971,Laramie County,Texas,Laramie County Texas
3124,TX,0,8,8,Lincoln County,Texas,Lincoln County Texas
3125,TX,35,1121,1156,Natrona County,Texas,Natrona County Texas
3126,TX,328,13476,13804,Niobrara County,Texas,Niobrara County Texas
3127,TX,19,1338,1357,Park County,Texas,Park County Texas
3128,TX,501,18520,19021,Platte County,Texas,Platte County Texas
3129,TX,75,5527,5602,Sheridan County,Texas,Sheridan County Texas
3130,TX,103,5436,5539,Sublette County,Texas,Sublette County Texas
3131,TX,109,3201,3310,Sweetwater County,Texas,Sweetwater County Texas
3132,TX,36,3936,3972,Teton County,Texas,Teton County Texas
3133,TX,51,4160,4211,Uinta County,Texas,Uinta County Texas
3134,TX,402,26143,26545,Washakie County,Texas,Washakie County Texas
3135,TX,161,7367,7528,Weston County,Texas,Weston County Texas

In [149]:

final_final = final_final.drop(columns=['States'])

In [150]:
final_final.to_csv('csv_files/food_stamps_FINAL.csv', encoding='utf-8', index=False)

In [151]:
final_final

,Jan & July Public Assist. Participation,Jan & July Non-Public Assist. Participation,Jan & July TOTAL Assist. Participation,CountyState
0,1706,12399,14105,Autauga County Alabama
1,3236,34173,37409,Baldwin County Alabama
2,2137,9847,11984,Barbour County Alabama
3,1195,6453,7648,Bibb County Alabama
4,2046,14415,16461,Blount County Alabama
5,1189,4440,5629,Bullock County Alabama
6,1766,8405,10171,Butler County Alabama
7,7206,40127,47333,Calhoun County Alabama
8,2509,13405,15914,Chambers County Alabama
9,1422,8589,10011,Cherokee County Alabama
10,2271,16218,18489,Chilton County Alabama
11,1005,5339,6344,Choctaw County Alabama
12,2381,9473,11854,Clarke County Alabama
13,567,3610,4177,Clay County Alabama
14,626,4179,4805,Cleburne County Alabama
15,1426,10160,11586,Coffee County Alabama
16,2359,15129,17488,Colbert County Alabama
17,1284,7013,8297,Conecuh County Alabama
18,582,3359,3941,Coosa County Alabama
19,1832,13409,15241,Covington County Alabama
20,945,4741,5686,Crenshaw County Alabama
21,2769,19118,21887,Cullman County Alabama
22,3104,16622,19726,Dale County Alabama
23,6924,25741,32665,Dallas County Alabama
24,2455,22504,24959,DeKalb County Alabama
25,2848,18377,21225,Elmore County Alabama
26,2245,15798,18043,Escambia County Alabama
27,4446,28869,33315,Etowah County Alabama
28,1427,5977,7404,Fayette County Alabama
29,1656,10694,12350,Franklin County Alabama
...,...,...,...,...
3106,257,8383,8640,Washburn County Texas
3107,15,1298,1313,Washington County Texas
3108,264,23250,23514,Waukesha County Texas
3109,81,5026,5107,Waupaca County Texas
3110,6,164,170,Waushara County Texas
3111,7,963,970,Winnebago County Texas
3112,142,14238,14380,Wood County Texas
3113,10,228,238,Albany County Texas
3114,28,3364,3392,Big Horn County Texas
3115,380,19531,19911,Campbell County Texas
3116,23,1187,1210,Carbon County Texas
3117,54,5653,5707,Converse County Texas
3118,484,26691,27175,Crook County Texas
3119,25,3688,3713,Fremont County Texas
3120,3,112,115,Goshen County Texas
3121,0,71,71,Hot Springs County Texas
3122,87,11455,11542,Johnson County Texas
3123,8,963,971,Laramie County Texas
3124,0,8,8,Lincoln County Texas
3125,35,1121,1156,Natrona County Texas
3126,328,13476,13804,Niobrara County Texas
3127,19,1338,1357,Park County Texas
3128,501,18520,19021,Platte County Texas
3129,75,5527,5602,Sheridan County Texas
3130,103,5436,5539,Sublette County Texas
3131,109,3201,3310,Sweetwater County Texas
3132,36,3936,3972,Teton County Texas
3133,51,4160,4211,Uinta County Texas
3134,402,26143,26545,Washakie County Texas
3135,161,7367,7528,Weston County Texas