# Make the dataframe to run Regressions on

In [229]:
#import modules
import re
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

## Import data with County and States together

In [230]:
df_wage = pd.read_csv('csv_files/wage_data_state.csv')
df_smoke = pd.read_csv('csv_files/smoking_FINAL.csv')
df_life = pd.read_csv('csv_files/life_expectancy_data_county.csv')
df_obesity = pd.read_csv('csv_files/obesity_FINAL.csv')
df_food = pd.read_csv('csv_files/food_stamps_FINAL.csv')
df_unemployment = pd.read_csv('csv_files/unemployment_FINAL.csv')

In [231]:
# Clean life by state

# Doing this here because it's in a weird formate
df_life['CountyState'] = df_life['County'].map(str) + " " +df_life['State']

df_life.head()

           County     State  Life expectancy 2010              CountyState
0  Autauga County   Alabama                 75.74  Autauga County  Alabama
1  Baldwin County   Alabama                 77.80  Baldwin County  Alabama
2  Barbour County   Alabama                 75.34  Barbour County  Alabama
3     Bibb County   Alabama                 74.13     Bibb County  Alabama
4   Blount County   Alabama                 76.41   Blount County  Alabama

In [232]:
len(df_smoke), len(df_life), len(df_food)

(3127, 3142, 3136)

In [233]:
df_smoke.head()

,County,Percent Smokers,State Ab,State,CountyState
0,Autauga County,25.8,Alabama,Alabama,Autauga County Alabama
1,Baldwin County,23.0,Alabama,Alabama,Baldwin County Alabama
2,Barbour County,26.8,Alabama,Alabama,Barbour County Alabama
3,Bibb County,30.1,Alabama,Alabama,Bibb County Alabama
4,Blount County,27.9,Alabama,Alabama,Blount County Alabama

In [234]:
df_life.head()

           County     State  Life expectancy 2010              CountyState
0  Autauga County   Alabama                 75.74  Autauga County  Alabama
1  Baldwin County   Alabama                 77.80  Baldwin County  Alabama
2  Barbour County   Alabama                 75.34  Barbour County  Alabama
3     Bibb County   Alabama                 74.13     Bibb County  Alabama
4   Blount County   Alabama                 76.41   Blount County  Alabama

In [235]:
# merging food to life and creating a final dataframe 

final_df = pd.merge(df_life, df_smoke.drop_duplicates(subset=['CountyState']), on='CountyState')
final_df.tail()

,County_x,State_x,Life expectancy 2010,CountyState,County_y,Percent Smokers,State Ab,State_y
3081,Sweetwater County,Wyoming,77.93,Sweetwater County Wyoming,Sweetwater County,25.6,Wyoming,Wyoming
3082,Teton County,Wyoming,82.95,Teton County Wyoming,Teton County,12.7,Wyoming,Wyoming
3083,Uinta County,Wyoming,77.51,Uinta County Wyoming,Uinta County,22.7,Wyoming,Wyoming
3084,Washakie County,Wyoming,78.77,Washakie County Wyoming,Washakie County,22.6,Wyoming,Wyoming
3085,Weston County,Wyoming,78.64,Weston County Wyoming,Weston County,24.6,Wyoming,Wyoming

In [236]:
# clean final
final_df.rename(columns={'County_x':'County', 'State_x':'State'}, inplace=True)

final_df = final_df.drop(columns=['County_y', 'State Ab', 'State_y'])
final_df['CountyState'].dtype

dtype('O')

In [237]:
#take out extra space in final_df county state
final_df['CountyState'] = final_df['CountyState'].apply(lambda x: x.replace("  ", " "))
df_food['CountyState'] = df_food['CountyState'].apply(lambda x: x.replace("  ", " "))

In [238]:
final_df.tail()

,County,State,Life expectancy 2010,CountyState,Percent Smokers
3081,Sweetwater County,Wyoming,77.93,Sweetwater County Wyoming,25.6
3082,Teton County,Wyoming,82.95,Teton County Wyoming,12.7
3083,Uinta County,Wyoming,77.51,Uinta County Wyoming,22.7
3084,Washakie County,Wyoming,78.77,Washakie County Wyoming,22.6
3085,Weston County,Wyoming,78.64,Weston County Wyoming,24.6

In [239]:
# merging food to final dataframe

something = pd.merge(df_food, final_df, on='CountyState', how='left').dropna()
something.tail()

,Jan & July Public Assist. Participation,Jan & July Non-Public Assist. Participation,Jan & July TOTAL Assist. Participation,CountyState,County,State,Life expectancy 2010,Percent Smokers
3095,197,14257,14454,Rusk County Texas,Rusk County,Texas,76.04,26.2
3101,332,24483,24815,Taylor County Texas,Taylor County,Texas,76.71,22.6
3107,15,1298,1313,Washington County Texas,Washington County,Texas,78.57,20.6
3112,142,14238,14380,Wood County Texas,Wood County,Texas,76.67,26.2
3122,87,11455,11542,Johnson County Texas,Johnson County,Texas,76.84,24.6

In [240]:
# merging obesity to final dataframe

final_w_o = pd.merge(df_obesity, something, on='CountyState', how='left').dropna()
final_w_o.tail()

,Percent Obese,CountyState,Jan & July Public Assist. Participation,Jan & July Non-Public Assist. Participation,Jan & July TOTAL Assist. Participation,County,State,Life expectancy 2010,Percent Smokers
2866,9447,Wood County Texas,142.0,14238.0,14380.0,Wood County,Texas,76.67,26.2
2973,19155,Montgomery County Virginia,3240.0,7444.0,10684.0,Montgomery County,Virginia,79.12,18.1
2977,2993,Northumberland County Virginia,2180.0,9979.0,12159.0,Northumberland County,Virginia,79.25,22.9
2979,8220,Orange County Virginia,3001.0,8868.0,11869.0,Orange County,Virginia,78.69,23.0
3169,19847,Jefferson County Wisconsin,502.0,6167.0,6669.0,Jefferson County,Wisconsin,80.20,22.3

In [241]:
# merging unemployment to final dataframe

final_w_un = pd.merge(df_unemployment, final_w_o, on='CountyState', how='left').dropna()
final_w_un.tail()

,Unemployment_rate_2010,CountyState,Percent Obese,Jan & July Public Assist. Participation,Jan & July Non-Public Assist. Participation,Jan & July TOTAL Assist. Participation,County,State,Life expectancy 2010,Percent Smokers
2857,9.1,Wood County Texas,9447,142.0,14238.0,14380.0,Wood County,Texas,76.67,26.2
2964,7.1,Montgomery County Virginia,19155,3240.0,7444.0,10684.0,Montgomery County,Virginia,79.12,18.1
2968,8.7,Northumberland County Virginia,2993,2180.0,9979.0,12159.0,Northumberland County,Virginia,79.25,22.9
2970,8.3,Orange County Virginia,8220,3001.0,8868.0,11869.0,Orange County,Virginia,78.69,23.0
3159,8.7,Jefferson County Wisconsin,19847,502.0,6167.0,6669.0,Jefferson County,Wisconsin,80.20,22.3

In [253]:
final_w_un['State'] = final_w_un['State'].apply(lambda x: x.strip())

In [254]:
df_wage['State'] = df_wage['State'].apply(lambda x: x.strip())

df_wage.tail()

                 State  Min Wage
46          Washington      9.19
47        WestVirginia      7.25
48           Wisconsin      7.25
49             Wyoming      5.15
50  DistrictofColumbia      8.25

In [264]:
final_w_un.tail(100)

,Unemployment_rate_2010,CountyState,Percent Obese,Jan & July Public Assist. Participation,Jan & July Non-Public Assist. Participation,Jan & July TOTAL Assist. Participation,County,State,Life expectancy 2010,Percent Smokers
2119,13.0,Carroll County Ohio,6202,2475.0,10545.0,13020.0,Carroll County,Ohio,78.56,28.0
2121,11.0,Clark County Ohio,33778,1263.0,8644.0,9907.0,Clark County,Ohio,76.42,28.3
2140,9.9,Hamilton County Ohio,167198,3344.0,10540.0,13884.0,Hamilton County,Ohio,77.46,23.5
2141,9.1,Hancock County Ohio,17022,7445.0,28964.0,36409.0,Hancock County,Ohio,79.34,23.4
2142,11.2,Hardin County Ohio,7262,4743.0,24096.0,28839.0,Hardin County,Ohio,76.89,27.5
2143,12.5,Harrison County Ohio,3595,8462.0,29690.0,38152.0,Harrison County,Ohio,76.41,30.6
2149,12.5,Jackson County Ohio,8102,911.0,6711.0,7622.0,Jackson County,Ohio,74.74,30.7
2150,14.5,Jefferson County Ohio,19302,2665.0,12792.0,15457.0,Jefferson County,Ohio,76.02,29.0
2151,9.7,Knox County Ohio,13920,44895.0,121919.0,166814.0,Knox County,Ohio,77.99,25.9
2152,9.7,Knox County Ohio,13920,2566.0,7993.0,10559.0,Knox County,Ohio,77.99,25.9
2156,11.8,Logan County Ohio,9839,957.0,5045.0,6002.0,Logan County,Ohio,77.28,27.0
2159,9.0,Madison County Ohio,9997,1884.0,14096.0,15980.0,Madison County,Ohio,77.32,27.6
2161,11.0,Marion County Ohio,16157,21631.0,83222.0,104853.0,Marion County,Ohio,77.16,30.8
2162,7.4,Medina County Ohio,35706,1405.0,5997.0,7402.0,Medina County,Ohio,80.13,20.9
2180,12.1,Richland County Ohio,29046,2755.0,10875.0,13630.0,Richland County,Ohio,77.87,28.3
2267,7.8,Stephens County Oklahoma,9763,468.0,21344.0,21812.0,Stephens County,Oklahoma,75.73,28.6
2272,6.7,Washington County Oklahoma,11653,235.0,20825.0,21060.0,Washington County,Oklahoma,77.90,27.1
2316,10.1,Bedford County Pennsylvania,12660,814.0,2638.0,3452.0,Bedford County,Pennsylvania,79.28,24.1
2321,7.4,Butler County Pennsylvania,39910,1012.0,14089.0,15101.0,Butler County,Pennsylvania,79.11,21.3
2332,6.8,Cumberland County Pennsylvania,45807,1358.0,9113.0,10471.0,Cumberland County,Pennsylvania,80.07,18.2
2339,8.5,Franklin County Pennsylvania,35757,442.0,3018.0,3460.0,Franklin County,Pennsylvania,79.71,21.7
2374,8.1,Washington County Pennsylvania,44212,2933.0,23340.0,26273.0,Washington County,Pennsylvania,78.24,24.3
2375,8.1,Washington County Pennsylvania,44212,11247.0,45724.0,56971.0,Washington County,Pennsylvania,78.24,24.3
2376,8.1,Wayne County Pennsylvania,12089,12585.0,55963.0,68548.0,Wayne County,Pennsylvania,78.06,26.1
2415,16.2,Lee County South Carolina,5702,3129.0,30265.0,33394.0,Lee County,SouthCarolina,73.12,27.5
2442,5.2,Clark County South Dakota,901,301.0,9871.0,10172.0,Clark County,SouthDakota,79.98,22.7
2451,4.4,Douglas County South Dakota,658,24.0,1596.0,1620.0,Douglas County,SouthDakota,80.78,21.4
2505,14.6,Carroll County Tennessee,7536,1909.0,11036.0,12945.0,Carroll County,Tennessee,74.08,26.2
2510,12.1,Clay County Tennessee,1870,5226.0,37988.0,43214.0,Clay County,Tennessee,74.68,26.2
2511,12.1,Clay County Tennessee,1870,2443.0,14640.0,17083.0,Clay County,Tennessee,74.68,26.2
...,...,...,...,...,...,...,...,...,...,...
2727,11.3,Jefferson County Texas,65411,7180.0,362197.0,369377.0,Jefferson County,Texas,76.04,25.4
2730,8.7,Johnson County Texas,34564,87.0,11455.0,11542.0,Johnson County,Texas,76.84,24.6
2761,8.4,Madison County Texas,3244,214.0,11232.0,11446.0,Madison County,Texas,76.94,25.8
2762,11.8,Marion County Texas,2624,0.0,127.0,127.0,Marion County,Texas,74.60,26.7
2764,6.3,Mason County Texas,846,80.0,6057.0,6137.0,Mason County,Texas,79.58,17.8
2780,12.7,Newton County Texas,3437,309.0,5426.0,5735.0,Newton County,Texas,74.92,27.7
2783,5.9,Ochiltree County Texas,1986,289.0,16617.0,16906.0,Ochiltree County,Texas,76.62,22.4
2785,11.7,Orange County Texas,19480,276.0,18592.0,18868.0,Orange County,Texas,74.51,27.8
2790,7.3,Pecos County Texas,3344,274.0,19270.0,19544.0,Pecos County,Texas,78.25,21.3
2791,9.7,Polk County Texas,11896,123.0,4179.0,4302.0,Polk County,Texas,73.17,29.4
2792,9.7,Polk County Texas,11896,128.0,8207.0,8335.0,Polk County,Texas,73.17,29.4
2793,6.3,Potter County Texas,28897,75.0,4262.0,4337.0,Potter County,Texas,74.33,27.3
2801,8.7,Refugio County Texas,1610,228.0,17472.0,17700.0,Refugio County,Texas,76.70,21.6
2803,9.2,Robertson County Texas,3764,491.0,32585.0,33076.0,Robertson County,Texas,75.90,23.8
2806,7.8,Rusk County Texas,13978,197.0,14257.0,14454.0,Rusk County,Texas,76.04,26.2
2811,6.2,San Saba County Texas,1406,161.0,3703.0,3864.0,San Saba County,Texas,78.24,24.2
2813,6.8,Scurry County Texas,3587,44.0,2084.0,2128.0,Scurry County,Texas,77.14,23.2
2826,6.8,Taylor County Texas,26673,132.0,9414.0,9546.0,Taylor County,Texas,76.71,22.6
2827,6.8,Taylor County Texas,26673,332.0,24483.0,24815.0,Taylor County,Texas,76.71,22.6
2835,11.8,Tyler County Texas,5043,44.0,3371.0,3415.0,Tyler County,Texas,75.76,28.4
2836,8.8,Upshur County Texas,8895,3892.0,239316.0,243208.0,Upshur County,Texas,75.34,25.9
2845,7.2,Washington County Texas,7099,15.0,1298.0,1313.0,Washington County,Texas,78.57,20.6
2849,7.8,Wichita County Texas,31462,118.0,8194.0,8312.0,Wichita County,Texas,75.54,25.5
2851,14.5,Willacy County Texas,4405,48.0,4098.0,4146.0,Willacy County,Texas,79.55,17.6
2856,9.1,Wood County Texas,9447,37.0,2101.0,2138.0,Wood County,Texas,76.67,26.2
2857,9.1,Wood County Texas,9447,142.0,14238.0,14380.0,Wood County,Texas,76.67,26.2
2964,7.1,Montgomery County Virginia,19155,3240.0,7444.0,10684.0,Montgomery County,Virginia,79.12,18.1
2968,8.7,Northumberland County Virginia,2993,2180.0,9979.0,12159.0,Northumberland County,Virginia,79.25,22.9
2970,8.3,Orange County Virginia,8220,3001.0,8868.0,11869.0,Orange County,Virginia,78.69,23.0
3159,8.7,Jefferson County Wisconsin,19847,502.0,6167.0,6669.0,Jefferson County,Wisconsin,80.20,22.3

In [267]:
# last to add min wage by state, not county
# last to add min wage by state, not countydf_ow = df_obesity.merge(df_wage, on=['State'], how='outer')

# final = final_w_un.merge(df_wage, on=['State'], how='left')
# final.head()


final = final_w_un.merge(df_wage, on='State', how='left')
final.tail()

#df_wage

,Unemployment_rate_2010,CountyState,Percent Obese,Jan & July Public Assist. Participation,Jan & July Non-Public Assist. Participation,Jan & July TOTAL Assist. Participation,County,State,Life expectancy 2010,Percent Smokers,Min Wage
551,9.1,Wood County Texas,9447,142.0,14238.0,14380.0,Wood County,Texas,76.67,26.2,7.25
552,7.1,Montgomery County Virginia,19155,3240.0,7444.0,10684.0,Montgomery County,Virginia,79.12,18.1,7.25
553,8.7,Northumberland County Virginia,2993,2180.0,9979.0,12159.0,Northumberland County,Virginia,79.25,22.9,7.25
554,8.3,Orange County Virginia,8220,3001.0,8868.0,11869.0,Orange County,Virginia,78.69,23.0,7.25
555,8.7,Jefferson County Wisconsin,19847,502.0,6167.0,6669.0,Jefferson County,Wisconsin,80.20,22.3,7.25

In [270]:
def get_the_wage(state):
    return df_wage[df_wage['State'] == state]['Min Wage'].values[0]

final_w_un['min_wage'] = final_w_un['State'].apply(lambda x: get_the_wage(x))

In [272]:
final_w_un.tail()

,Unemployment_rate_2010,CountyState,Percent Obese,Jan & July Public Assist. Participation,Jan & July Non-Public Assist. Participation,Jan & July TOTAL Assist. Participation,County,State,Life expectancy 2010,Percent Smokers,min_wage
2857,9.1,Wood County Texas,9447,142.0,14238.0,14380.0,Wood County,Texas,76.67,26.2,7.25
2964,7.1,Montgomery County Virginia,19155,3240.0,7444.0,10684.0,Montgomery County,Virginia,79.12,18.1,7.25
2968,8.7,Northumberland County Virginia,2993,2180.0,9979.0,12159.0,Northumberland County,Virginia,79.25,22.9,7.25
2970,8.3,Orange County Virginia,8220,3001.0,8868.0,11869.0,Orange County,Virginia,78.69,23.0,7.25
3159,8.7,Jefferson County Wisconsin,19847,502.0,6167.0,6669.0,Jefferson County,Wisconsin,80.20,22.3,7.25